from scipy.integrate import solve_ivp as solve_ivp
from scipy.optimize import root_scalar as root_scalar

def thetadic05(): ...
def f05(t, y, phi, phit, theta, te): ...
def thetadic06(): ...
def f06(t, y, phi, phit, theta, te): ...
def thetadic07(): ...
def f07(t, y, phi, phit, theta, te): ...
def thetadic11(): ...
def f11(t, y, phi, phit, theta, te): ...
def thetadic08(): ...
def f08(t, y, phi, phit, theta, te): ...
def thetadic09(): ...
def f09(t, y, phi, phit, theta, te): ...
def thetadic12(): ...
def f12(t, y, phi, phit, theta, te): ...
def thetadic13(): ...
def f13(t, y, phi, phit, theta, te): ...
def thetadic14(): ...
def f14(t, y, phi, phit, theta, te): ...
def thetadic14p(): ...
def f14p(t, y, phi, phit, theta, te): ...
def thetadic14s(): ...
def f14s(t, y, phi, phit, theta, te): ...
def thetadic15(): ...
def f15(t, y, phi, phit, theta, te): ...
def thetadic16(): ...
def f16(t, y, phi, phit, theta, te): ...
def thetadic17(): ...
def f17(t, y, phi, phit, theta, te): ...
def thetadic22(): ...
def f22(t, y, phi, phit, theta, te): ...
